In [20]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix

In [15]:
data = pd.read_csv('../data/fruit_data.csv')
x_data=data.iloc[:,1:]
y_data=data.iloc[:,0]
print(x_data.shape)
print(y_data.shape)

(59, 4)
(59,)


In [16]:
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data)

In [17]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

C:\Users\张帅\AppData\Roaming\Python\Python36\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\张帅\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\张帅\AppData\Roaming\Python\Python36\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\张帅\AppData\Roaming\Python\Python36\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [18]:
mlp=MLPClassifier(hidden_layer_sizes=(100,50),max_iter=500)
mlp.fit(x_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [19]:
predictions = mlp.predict(x_test)
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

       apple       1.00      0.43      0.60         7
       lemon       0.50      1.00      0.67         1
    mandarin       1.00      1.00      1.00         2
      orange       0.50      0.80      0.62         5

   micro avg       0.67      0.67      0.67        15
   macro avg       0.75      0.81      0.72        15
weighted avg       0.80      0.67      0.66        15



In [21]:
print(confusion_matrix(y_test,predictions))

[[3 0 0 4]
 [0 1 0 0]
 [0 0 2 0]
 [0 1 0 4]]
