In [2]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB

In [3]:
iris=datasets.load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target)

In [4]:
mul_nb=GaussianNB()
mul_nb.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [6]:
print(classification_report(mul_nb.predict(x_test),y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.93      0.87      0.90        15
           2       0.86      0.92      0.89        13

   micro avg       0.92      0.92      0.92        38
   macro avg       0.93      0.93      0.93        38
weighted avg       0.92      0.92      0.92        38



In [7]:
print(confusion_matrix(mul_nb.predict(x_test),y_test))

[[10  0  0]
 [ 0 13  2]
 [ 0  1 12]]
